---
title: "535_HW5"
author: "Shayna Warner"
date: "11/18/2019==
output: pdf_document
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(reshape2)
library(readr)
library(forcats)
library(tigris)
library(sf)

library(tibble)
library(ggplot2)
library(maps)

```



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,options(tigris_use_cache = TRUE))

#load in the homicide data set, view, filer by denver

homicide_data_set <- read.csv("data_HW5/homicide-data.csv") %>%
  filter(city== "Denver")%>%
  select(lat,lon, disposition,victim_race)

Denver_data <- homicide_data_set
nrow(Denver_data)
```


```{r zip codes}
#plot by zip codes

denver_zipcodes <- zctas(cb=TRUE,starts_with=c("802"),class="sf")
plot(denver_zipcodes)
```

```{r race}
#filter by race
race <- Denver_data %>%
  group_by(victim_race) %>%
  mutate(count=n()) %>%
  arrange(desc(count)) %>%
  ungroup() %>%
  filter(victim_race==c("Black","White","Hispanic"))
race
```
#Create Map
```{r map,fig.width=30}
#set Denver with crs code
denver_crs <- race%>%
  filter(!is.na(lat))%>%
  st_as_sf(coords=c("lon","lat")) %>%
  st_set_crs(4269)
```

```{r}
#seperate into solved vs unsolved
denver_disp <- denver_crs %>%
  mutate(disposition= factor(disposition,levels = c("Closed without arrest",
                                                    "Closed by arrest",
                                                    "Open/No arrest"),
                             labels=c("unsolved","unsolved","solved")))
denver_disp
                               
                               
```
```

```{r, fig.width=30}
#map by homicide areas in the city, solved vs unsolved
map<- ggplot()+
  geom_sf(data = denver_zipcodes,color= "lightgray")+
  geom_sf(data = denver_disp,aes(color=factor(victim_race)),show.legend='point')+
  facet_wrap(~disposition,ncol=1)+
  ggtitle("Homicide cases in Denver, Co")+
  labs(x="Longitude",y="Latitude")+
  theme(axis.text.x=element_text(angle=90,hjust=1))


map
```


```